i686-w64-mingw32-gcc ^
-mms-bitfields -march=i686 -std=c99 ^
-ID:\usr\vips-dev-8.14\include ^
-ID:\usr\vips-dev-8.14\include\glib-2.0 ^
-ID:\usr\vips-dev-8.14\lib\glib-2.0\include ^
t_try264.c ^
t_generate.c ^
main.c ^
-LD:\usr\vips-dev-8.14\lib ^
-lvips ^
-lz ^
-ljpeg ^
-lstdc++ ^
-lxml2 ^
-lfftw3 ^
-lm ^
-llcms2 ^
-lopenslide ^
-lcfitsio ^
-lpangoft2-1.0 ^
-ltiff ^
-lexif ^
-lpango-1.0 ^
-lfreetype ^
-lfontconfig ^
-lgobject-2.0 ^
-lgmodule-2.0 ^
-lgthread-2.0 ^
-lglib-2.0 ^
-lintl ^
-o main.exe
